
[FRAME]
LOGLEVEL = "DEBUG"
IMG_SIZE = [
    1024,
    600,
]
MODEL = ""
DUMMY = false
DELAY = 10
PLUGINS_AVAILABLE = [
    "ledstrip",
    "loadimgfolder",
    "loadimgurl",
    "clocks",
    "samsungframe",
    "dummyframe"
]
PLUGINS_ACTIVE = [
    "loadimgartsy",
    "dummyframe",
]

[LOADIMGURL]
IMG_SOURCE_PATH = "https://random.imagecdn.app/1024/600"
HTTP_DOWNLOAD_LIMIT = 10
DELAY = 10

