

[FRAME]
LOGLEVEL = "INFO"
IMG_SIZE = [
    1024,
    600,
]
DELAY = 60

[PLUGUNS]

ACTIVE = [
    "LOADIMGURL",
    "SAMSUNGFRAME",
]

[SAMSUNGFRAME]
MODEL = ""

[LOADIMGURL]
IMG_SOURCE_PATH = "https://random.imagecdn.app/1024/600"
HTTP_DOWNLOAD_LIMIT = 10
DELAY = 10

[LOADIMGARTSY]
HTTP_DOWNLOAD_LIMIT=5

[REMOTE]
ADDRESS="*"
PORT=8088