[FRAME]
dynaconf_merge=true
MODEL = ""

[PLUGINS]
ACTIVE = [
    "nightmode",
    "clocks",
    "loadimgartsy",
    "dummyframe",
    "remote"
]

[NIGHTMODE]
    "TIMES" = [["08:00", "day"],
        ["23:40", "night"],
        ]
    "NIGHT_BRIGHTNESS" = 10

[REMOTE]
ADDRESS="localhost"
PORT=8088